# Generated by Django 4.1.1 on 2022-10-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-create_date',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
