# Generated by Django 4.1.1 on 2022-09-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_courses_lesson_courseteachers'),
    ]

    operations = [
    ]
