# Generated by Django 4.1.1 on 2022-09-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_newDataToTable'),
    ]

    operations = [
    ]
